### ISSUE TITLE
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by jinze1994** [liamcli/randomNAS_release#5]
Got the RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED when executing the CNN model.

### Traceback
```
(torch) baijin@pku:~/Code/randomNAS/searchers$ python random_weight_share.py
07/19 12:41:24 PM Namespace(batch_size=64, benchmark='cnn', config='search', epochs=100, eval_only=0, grad_clip=0.25, init_channels=16, save_dir=None, seed=100)
[Errno 2] No such file or directory: './result/cnn/random/trial100/weights.pt'
07/19 12:41:31 PM param size = 1.930618MB
07/19 12:41:31 PM param size: 1930618
07/19 12:41:31 PM Args: {'data': '/home/baijin/Dataset/cifar10/', 'epochs': 100, 'learning_rate': 0.025, 'batch_size': 64, 'learning_rate_min': 0.001, 'momentum': 0.9, 'weight_decay': 0.0003, 'init_channels': 16, 'layers': 8, 'drop_path_prob': 0.3, 'grad_clip': 0.25, 'train_portion': 0.5, 'seed': 100, 'log_interval': 50, 'save': './result/cnn/random/trial100', 'gpu': 0, 'cuda': True, 'cutout': False, 'cutout_length': 16, 'report_freq': 50}
07/19 12:41:31 PM Model total parameters: 1930618
07/19 12:41:31 PM budget: 39062
Traceback (most recent call last):
  File "random_weight_share.py", line 184, in <module>
    main(args)
  File "random_weight_share.py", line 155, in main
    searcher.run()
  File "random_weight_share.py", line 75, in run
    self.model.train_batch(arch)
  File "/home/baijin/Code/randomNAS/benchmarks/cnn/darts/darts_wrapper_discrete.py", line 157, in train_batch
    logits = self.model(input, discrete=True)
  File "/home/baijin/Lib/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/baijin/Code/l-darts/cnn/model_search.py", line 104, in forward
    s0 = s1 = self.stem(input)
  File "/home/baijin/Lib/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/baijin/Lib/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/baijin/Lib/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/baijin/Lib/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/home/baijin/Lib/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED
```

### Environment
```
Collecting environment information...
PyTorch version: 0.3.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 418.56
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.3
[conda] blas                      1.0                         mkl    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
[conda] cuda90                    1.0                  h6433d27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] mkl                       2018.0.3                      1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
[conda] pytorch                   0.3.1           py36_cuda9.0.176_cudnn7.0.5_2  [cuda90]  https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torchvision               0.2.0                    py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main

```

I tried `python train.py --auxiliary --cutout` in [liamcli/darts/cnn](https://github.com/liamcli/darts/tree/master/cnn) and I encounted the same `RuntimeError: CUDNN_STATUS_EXECUTION_FAILED` error.

Could you please help me to check what's the problem with the environments and the DARTS? Thank you very much.

**Comment by jinze1994** [comment]
Seem like it is the Pytorch version problem. The PyTorch 0.3.1 with cuda10.0 has a compatibility issue on 2080Ti, and cuda9.0 seems to trigger this problem on 2080Ti.
